### ISSUE TITLE
Add option for other rolls

### ISSUE THREAD

**Issue by teo-cay** [eupolemo/fvtt-l5r4ed-dice-roller#16]
it would be great to be able to do other kinds of rolls like untrained rolls where 10 dont explode

**Comment by eupolemo** [comment]
Yeah, it is a good ideal. I'm adding to the backlog and as soon as i can, i'll code it.

**Comment by teo-cay** [comment]
just in case it helps: 
untrained rolls in foundry notation would be: `${roll}d10k${keep}` (not exploding)
emphasis rolls in foundry notation would be: `${roll}d10r1k${keep}x10` (re roll 1's once and explode 10's)

**Comment by eupolemo** [comment]
- [x]  Add untrained tag (u5k5) = untrained 5k5 (don't explode);
- [x]  Add emphasis roll (e5k5) = emphasis 5k5 (reroll 1, one time);
- [x]  Add untrained syntax to documentation;
- [x] Add emphasis syntax to documentation;
